* moonlander
** RULES
*** THUMBS
**** on all layers the same
*** e
**** e
***** NOT
****** on SWITCH
******* as =CTRL=
****** on SIDE
******* as =SPACE=
** NAMES
*** keys
upperCase and in =
**** layers
***** MO(layer)
momentarily activates layer. 
As soon as you let go of the key, the layer is deactivated.
***** LM(layer, mod)
Momentarily activates layer (like MO), but with modifier(s) mod active. 
Only supports layers 0-15 and the left modifiers: MOD_LCTL, MOD_LSFT, MOD_LALT, MOD_LGUI (note the use of MOD_ constants instead of KC_). 
These modifiers can be combined using bitwise OR, e.g. LM(_RAISE, MOD_LCTL | MOD_LALT).
***** LT(layer, kc)
momentarily activates layer when held, and sends kc when tapped. 
Only supports layers 0-15.
***** OSL(layer)
momentarily activates layer until the next key is pressed. 
See One Shot Keys for details and additional functionality.
***** TG(layer)
toggles layer, activating it if it's inactive and vice versa
***** TO(layer)
activates layer and de-activates all other layers (except your default layer). 
This function is special, because instead of just adding/removing one layer to your active layer stack, it will completely replace your current active layers, uniquely allowing you to replace higher layers with a lower one. 
This is activated on keydown (as soon as the key is pressed).
***** TT(layer)
Layer Tap-Toggle. 
If you hold the key down, layer is activated, and then is de-activated when you let go (like MO). 
If you repeatedly tap it, the layer will be toggled on or off (like TG). 
It needs 5 taps by default, but you can change this by defining TAPPING_TOGGLE -- for example, #define TAPPING_TOGGLE 2 to toggle on just two taps.
*** switches
in *
*{l,r}{T,I,M,R,P}{1,2,3,4,5,6,7,8,9,10,11,12}*
hand finger number-of-switch
*** layers
upperCase and in ~
~RSTHD~
~QWERTY~
~SYMBOLS~
~MEDIAMOUSE~
~NUM~
~MOON~
~FUNCTION~
~DIACRITICA~
~EMOJI~
~HUB~
** INFO
*** modifier vs layer
modifier work on xkb
layerSwitches on qmk
** TODO TODOS
*** create MIRROR
*** change switches names to \**
*** layer for words
go
python
Rust
Dart
Flutter
englisch
deutsch

